pub mod commands;
pub mod db;
pub mod errors;
pub mod metadata;
pub mod models;
pub mod scanner;
pub mod thumbnail;

use db::Database;
use scanner::archive_reader;
use std::collections::HashMap;
use std::sync::Mutex;
use tauri::Manager;

/// Simple LRU-style cache for archive page bytes.
/// Keyed by (archive_path, entry_name). Evicts entries older than 5 minutes.
pub(crate) struct ArchiveCache {
    entries: HashMap<String, (Vec<u8>, std::time::Instant)>,
    max_entries: usize,
}

impl ArchiveCache {
    fn new(max_entries: usize) -> Self {
        Self {
            entries: HashMap::new(),
            max_entries,
        }
    }

    fn get(&mut self, key: &str) -> Option<Vec<u8>> {
        if let Some((bytes, instant)) = self.entries.get(key) {
            // Evict if older than 5 minutes
            if instant.elapsed().as_secs() > 300 {
                self.entries.remove(key);
                return None;
            }
            Some(bytes.clone())
        } else {
            None
        }
    }

    fn insert(&mut self, key: String, bytes: Vec<u8>) {
        // Evict oldest entries if cache is full
        if self.entries.len() >= self.max_entries {
            // Find and remove the oldest entry
            if let Some(oldest_key) = self
                .entries
                .iter()
                .max_by_key(|(_, (_, instant))| instant.elapsed())
                .map(|(k, _)| k.clone())
            {
                self.entries.remove(&oldest_key);
            }
        }
        self.entries.insert(key, (bytes, std::time::Instant::now()));
    }
}

#[derive(Clone)]
pub struct AppState {
    pub(crate) database: std::sync::Arc<Database>,
    pub(crate) archive_cache: std::sync::Arc<Mutex<ArchiveCache>>,
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .register_uri_scheme_protocol("archive", |app_handle, request| {
            // Parse URL generated by convertFileSrc(path, "archive").
            let uri = request.uri().to_string();

            // Extract path and query from the URI
            let (encoded_path, entry_name) = parse_archive_uri(&uri);

            let archive_path = match percent_encoding::percent_decode_str(&encoded_path)
                .decode_utf8()
                .map(|s| s.to_string())
            {
                Ok(path) => std::path::PathBuf::from(path),
                Err(_) => {
                    return tauri::http::Response::builder()
                        .status(400)
                        .body(format!("Invalid archive path in URI: {uri}").into_bytes())
                        .unwrap();
                }
            };

            if !archive_path.exists() {
                return tauri::http::Response::builder()
                    .status(404)
                    .body(format!("Archive not found: {}", archive_path.display()).into_bytes())
                    .unwrap();
            }

            let decoded_entry = match percent_encoding::percent_decode_str(&entry_name)
                .decode_utf8()
                .map(|s| s.to_string())
            {
                Ok(name) => name,
                Err(_) => {
                    return tauri::http::Response::builder()
                        .status(400)
                        .body(format!("Invalid entry name in URI: {uri}").into_bytes())
                        .unwrap();
                }
            };

            // Check cache first
            let cache_key = format!("{}|{}", archive_path.display(), decoded_entry);
            let state: tauri::State<AppState> = app_handle.app_handle().state::<AppState>();
            {
                let mut cache = state.archive_cache.lock().unwrap();
                if let Some(cached_bytes) = cache.get(&cache_key) {
                    let mime = archive_reader::mime_from_entry_name(&decoded_entry);
                    return tauri::http::Response::builder()
                        .status(200)
                        .header("Content-Type", mime)
                        .header("Cache-Control", "public, max-age=86400")
                        .body(cached_bytes.clone())
                        .unwrap();
                }
            }

            match archive_reader::read_archive_entry(&archive_path, &decoded_entry) {
                Ok(bytes) => {
                    // Store in cache
                    {
                        let mut cache = state.archive_cache.lock().unwrap();
                        cache.insert(cache_key, bytes.clone());
                    }
                    let mime = archive_reader::mime_from_entry_name(&decoded_entry);
                    tauri::http::Response::builder()
                        .status(200)
                        .header("Content-Type", mime)
                        .header("Cache-Control", "public, max-age=86400")
                        .body(bytes)
                        .unwrap()
                }
                Err(e) => tauri::http::Response::builder()
                    .status(500)
                    .body(e.to_string().into_bytes())
                    .unwrap(),
            }
        })
        .setup(|app| {
            let database = Database::new(&app.handle())?;
            app.manage(AppState {
                database: std::sync::Arc::new(database),
                archive_cache: std::sync::Arc::new(Mutex::new(ArchiveCache::new(64))),
            });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::repositories::scan_repository,
            commands::repositories::auto_scan_repositories,
            commands::repositories::list_repositories,
            commands::repositories::remove_repository,
            commands::archive::get_archive_cover_entry,
            commands::bookmark::list_bookmarks,
            commands::bookmark::create_bookmark,
            commands::bookmark::delete_bookmark,
            commands::bookmark::is_page_bookmarked,
            commands::library::list_books,
            commands::library::ensure_book_thumbnails,
            commands::library::list_favorite_books,
            commands::library::list_book_tags,
            commands::library::list_favorite_collections,
            commands::library::create_favorite_collection,
            commands::library::rename_favorite_collection,
            commands::library::delete_favorite_collection,
            commands::library::add_book_to_favorite_collection,
            commands::library::add_books_to_favorite_collection,
            commands::library::remove_book_from_favorite_collection,
            commands::library::remove_books_from_favorite_collection,
            commands::library::move_books_between_favorite_collections,
            commands::library::remove_books_from_all_favorite_collections,
            commands::library::list_book_favorite_collections,
            commands::library::set_book_favorite,
            commands::library::rename_book_title,
            commands::library::reset_book_title,
            commands::library::get_book,
            commands::library::list_book_chapters,
            commands::reader::list_chapter_pages,
            commands::reader::update_book_progress,
            commands::reader::list_reading_history,
            commands::settings::ping,
            commands::settings::get_reader_settings,
            commands::settings::save_reader_settings,
            commands::settings::get_library_view_settings,
            commands::settings::save_library_view_settings,
        ])
        .run(tauri::generate_context!())
        .expect("failed to run InkReader");
}

/// Parse an archive image URI into (encoded_archive_path, encoded_entry_name).
/// Handles both archive://host/{encoded_path}?entry=... and Tauri dev URLs.
fn parse_archive_uri(uri: &str) -> (String, String) {
    let (base, query) = uri.split_once('?').unwrap_or((uri, ""));
    let encoded_entry = query
        .split('&')
        .find_map(|part| part.strip_prefix("entry="))
        .unwrap_or_default()
        .to_string();

    let encoded_path = if let Some((_, rest)) = base.split_once("://") {
        rest.split_once('/')
            .map(|(_, path)| path)
            .unwrap_or_default()
    } else {
        base
    };

    (encoded_path.to_string(), encoded_entry)
}

#[cfg(test)]
mod tests {
    use super::parse_archive_uri;

    #[test]
    fn parses_archive_protocol_uri() {
        let (path, entry) = parse_archive_uri("archive://localhost/F%3A%5Cbook.cbz?entry=0001.jpg");

        assert_eq!(path, "F%3A%5Cbook.cbz");
        assert_eq!(entry, "0001.jpg");
    }

    #[test]
    fn parses_tauri_asset_host_uri() {
        let (path, entry) =
            parse_archive_uri("archive://asset.localhost/F%3A%5Cbook.cbz?entry=dir%2F0001.jpg");

        assert_eq!(path, "F%3A%5Cbook.cbz");
        assert_eq!(entry, "dir%2F0001.jpg");
    }

    #[test]
    fn parses_tauri_dev_uri() {
        let (path, entry) =
            parse_archive_uri("http://archive.localhost/F%3A%5Cbook.cbz?entry=dir%2F0001.jpg");

        assert_eq!(path, "F%3A%5Cbook.cbz");
        assert_eq!(entry, "dir%2F0001.jpg");
    }
}
